version: '3.1'

services:
  db:
    build:
      context: ./db
    restart: always
    ports:
      - 9906:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    build:
      context: ./adminer
    restart: always
    ports:
      - 9090:8080
    depends_on:
      - db  # 确保 db 服务先启动

  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - "8083:80"
      - "443:443"
    depends_on:
      - db  # 确保 db 服务先启动
